### ISSUE TITLE
/paketal çalışmıyor

### ISSUE THREAD

**Issue by Jelibonzai** [DaePlugins/RpMarket#1]
Merhaba Dae, rica etsem bunu düzeltir misin. Kolay gelsin bu arada çalışmlarında

**Comment by cemahseri** [comment]
Unturned'ı ve eklentileri geliştirmeyi tamamıyla bıraktım. Bırakmadan önce her eklenti sorunsuz çalışıyordu, ki bu da eklentilerin oyuna gelen güncellemelerden dolayı bozulmuş olduğunu gösteriyor. Ne diye düzelteyim? Oyuna gelecek bir sonraki güncelleme bozsun diye mi? Bu yüzden hayır, düzeltmem. Teşekkürler.

**Comment by Jelibonzai** [comment]
Haklısınız.
